apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csv-logs
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi