#!/bin/sh
# UAT / smoke test for the Defguard WireGuard-VPN management stack (1.4.x pair).
# Brings up the control plane (postgres + core), provisions a VPN network
# through the real API, then joins the gateway and asserts it connects to core
# over gRPC and brings up the WireGuard tunnel interface.
#
#   ./run-uat.sh           # bring up, assert, leave running
#   ./run-uat.sh --down    # tear down and drop generated state
#
# Stability: every stage is gated (ensure_stable stops any crash-looping
# container instead of letting podman restart it unthrottled), and the compose
# file bounds restarts (on-failure:5) and memory. The gateway's wg interface
# uses the host kernel `wireguard` module (auto-loaded on interface creation).
set -u

cd "$(dirname "$0")"
. ../../ci/net-uat-lib.sh

STACK=defguard
COMPOSE_FILE=../docker-compose.yml
API=http://localhost:8000

if [ "${1:-}" = "--down" ]; then
    net_down
    exit 0
fi

# api_session — log in as admin, print the session cookie value. The cookie is
# scoped Domain=localhost, so the API is driven via localhost from the host.
api_session() {
    curl -s -D - -o /dev/null --max-time 10 -X POST "$API/api/v1/auth" \
        -H 'Content-Type: application/json' \
        -d "{\"username\":\"admin\",\"password\":\"$ADMIN_PW\"}" \
        | sed -n 's/.*defguard_session=\([^;]*\).*/\1/Ip'
}

say "== Defguard VPN UAT (control plane + gateway gRPC + tunnel)"

ADMIN_PW="$(openssl rand -hex 12)"
cat > .env <<EOF
# Generated by run-uat.sh — not for production use.
CORE_IMAGE=ghcr.io/defguard/defguard:1.4.0
GATEWAY_IMAGE=ghcr.io/defguard/gateway:1.4.0
POSTGRES_IMAGE=docker.io/library/postgres:18-alpine
POSTGRES_DB=defguard
POSTGRES_USER=defguard
POSTGRES_PASSWORD=$(openssl rand -hex 16)
DEFGUARD_AUTH_SECRET=$(openssl rand -hex 24)
DEFGUARD_GATEWAY_SECRET=$(openssl rand -hex 24)
DEFGUARD_YUBIBRIDGE_SECRET=$(openssl rand -hex 24)
DEFGUARD_SECRET_KEY=$(openssl rand -hex 40)
DEFGUARD_DEFAULT_ADMIN_PASSWORD=$ADMIN_PW
DEFGUARD_URL=http://localhost:8000
DEFGUARD_COOKIE_DOMAIN=localhost
DEFGUARD_COOKIE_INSECURE=true
BIND_ADDR=127.0.0.1
CORE_HTTP_PORT=8000
WG_PORT=51820
NET_SUBNET=172.32.10.0/24
COMPOSE_NET_NAME=${STACK}-net-uat
DB_VOLUME=${STACK}-net-uat-db
DEFGUARD_TOKEN=
EOF

net_init

say "-- stage 1: database"
up db || { net_down; exit 1; }
ensure_running defguard-db
ensure_stable defguard-db 6 || { net_report; exit 1; }
wait_healthy defguard-db 90 || { dumplog defguard-db; net_report; exit 1; }

say "-- stage 2: core control plane"
up core || { net_down; exit 1; }
ensure_running defguard-core
ensure_stable defguard-core 9 || { net_report; exit 1; }
wait_healthy defguard-core 120 || { dumplog defguard-core; net_report; exit 1; }
wait_http "$API/api/v1/health" 60 '^200$' || { dumplog defguard-core; net_report; exit 1; }

say "== checks"
check 200 "core reports healthy" "$API/api/v1/health"

SESSION="$(api_session)"
[ -n "$SESSION" ] && pass "admin authenticates against core" \
    || { fail "admin authenticates against core" "no session"; net_report; exit 1; }

say "-- stage 3: provision a VPN network"
_net="$(curl -s --max-time 10 -H "Cookie: defguard_session=$SESSION" -X POST "$API/api/v1/network" \
    -H 'Content-Type: application/json' \
    -d '{"name":"main-vpn","address":"10.0.50.1/24","port":51820,"endpoint":"127.0.0.1","allowed_ips":"10.0.50.0/24","dns":null,"allowed_groups":[],"mfa_enabled":false,"keepalive_interval":25,"peer_disconnect_threshold":180,"acl_enabled":false,"acl_default_allow":false}')"
NETID="$(printf '%s' "$_net" | python3 -c 'import sys,json;print(json.load(sys.stdin).get("id",""))' 2>/dev/null)"
[ -n "$NETID" ] && pass "VPN network provisioned via API" "id=$NETID" \
    || { fail "VPN network provisioned via API" "$(printf '%s' "$_net" | head -c 120)"; net_report; exit 1; }

TOKEN="$(curl -s --max-time 10 -H "Cookie: defguard_session=$SESSION" "$API/api/v1/network/$NETID/token" \
    | python3 -c 'import sys,json;print(json.load(sys.stdin).get("token",""))' 2>/dev/null)"
[ -n "$TOKEN" ] && pass "core minted a gateway token" \
    || { fail "core minted a gateway token" "empty"; net_report; exit 1; }

say "-- stage 4: gateway joins over gRPC"
sed -i "s#^DEFGUARD_TOKEN=.*#DEFGUARD_TOKEN=$TOKEN#" .env
up gateway || { net_down; exit 1; }
ensure_running defguard-gateway
ensure_stable defguard-gateway 9 || { net_report; exit 1; }

# The gateway connects to core over gRPC; core records it as connected.
_i=0; _conn=""
while [ "$_i" -lt 40 ]; do
    _conn="$(curl -s --max-time 10 -H "Cookie: defguard_session=$SESSION" "$API/api/v1/network/$NETID/gateways" \
        | python3 -c 'import sys,json;d=json.load(sys.stdin);print(any(g.get("connected") for g in d))' 2>/dev/null)"
    [ "$_conn" = "True" ] && break
    _i=$((_i+3)); sleep 3
done
[ "$_conn" = "True" ] && pass "gateway connected to core over gRPC" \
    || { fail "gateway connected to core over gRPC" "${_conn:-no reply}"; dumplog defguard-gateway; }

# The gateway configured the kernel WireGuard interface.
if $RUNTIME exec defguard-gateway wg show wg0 >/dev/null 2>&1; then
    pass "gateway brought up the WireGuard tunnel interface" "wg0"
else
    fail "gateway brought up the WireGuard tunnel interface" "no wg0"
    dumplog defguard-gateway
fi

if net_report; then
    say ""
    say "Core UI:   $API   (admin / $ADMIN_PW)"
    say "Tear down: ./run-uat.sh --down"
fi
net_report
