input {
  beats {
    port => 5044
  }
  tcp {
    port => 50000
    codec => json_lines
  }
  udp {
    port => 5140
    codec => json
  }
}

filter {
  if ![data_stream][dataset] {
    mutate { add_field => { "[data_stream][dataset]" => "generic" } }
  }
  if ![data_stream][namespace] {
    mutate { add_field => { "[data_stream][namespace]" => "default" } }
  }
  mutate { add_field => { "[data_stream][type]" => "logs" } }
}

output {
  elasticsearch {
    hosts => ["https://elasticsearch:9200"]
    user => "elastic"
    password => "${ELASTIC_PASSWORD:-}"
    ssl_enabled => true
    ssl_certificate_authorities => ["/usr/share/logstash/config/certs/ca/ca.crt"]
    data_stream => true
    data_stream_auto_routing => true
  }
}
