apiVersion: v1
kind: ConfigMap
metadata:
  name: mw-agent-config
  namespace: monitoring
data:
  otel-config.yaml: |
    receivers:
      hostmetrics:
        collection_interval: 10s
        scrapers:
          cpu: {}
          memory: {}
          disk: {}
          filesystem: {}
          network: {}
      otlp:
        protocols:
          grpc: {}
          http: {}
    processors:
      batch: {}
    exporters:
      otlp:
        endpoint: "${env:MW_TARGET}"
        headers:
          Authorization: "${env:MW_API_KEY}"
    service:
      pipelines:
        metrics:
          receivers: [hostmetrics]
          processors: [batch]
          exporters: [otlp]
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp]