#!/bin/sh
# Render the stack's compose artifacts from stack.yaml:
#   .env                       compose environment
#   tinyauth.env               Keycloak OIDC client id/secret
#   keycloak/realm-sonar.json  imported realm (realm, client, users, groups)
#
# Blank secrets in stack.yaml are generated once and persisted to .env /
# tinyauth.env (both gitignored); re-runs reuse them. TLS material is not
# generated here — supply real certificates in stack.tls_dir for production
# (the UAT harness generates a local CA for testing).
#
#   scripts/render.sh [path/to/stack.yaml]
set -eu

HERE="$(cd "$(dirname "$0")" && pwd)"
STACK_DIR="$(cd "$HERE/.." && pwd)"
CONFIG="${1:-$STACK_DIR/stack.yaml}"

command -v python3 >/dev/null 2>&1 || { echo "!! python3 required" >&2; exit 1; }

STACK_DIR="$STACK_DIR" CONFIG="$CONFIG" python3 - <<'PY'
import json, os, secrets, string, sys
try:
    import yaml
except ImportError:
    sys.exit("!! python3 yaml (PyYAML) required")

stack_dir = os.environ["STACK_DIR"]
cfg_path = os.environ["CONFIG"]
with open(cfg_path) as f:
    cfg = yaml.safe_load(f)

st = cfg["stack"]; hosts = cfg["hosts"]; imgs = cfg["images"]; kc = cfg["keycloak"]
sec = cfg.get("secrets") or {}

def rand(n=24):
    a = string.ascii_letters + string.digits
    return "".join(secrets.choice(a) for _ in range(n))

# Reuse secrets already written to .env / tinyauth.env for idempotency.
env_path = os.path.join(stack_dir, ".env")
existing = {}
if os.path.exists(env_path):
    for line in open(env_path):
        if "=" in line and not line.startswith("#"):
            k, v = line.rstrip("\n").split("=", 1); existing[k] = v
ta_path = os.path.join(stack_dir, "tinyauth.env")
if os.path.exists(ta_path):
    for line in open(ta_path):
        if "=" in line and not line.startswith("#"):
            k, v = line.rstrip("\n").split("=", 1); existing[k] = v

def want(secret_key, env_key):
    return sec.get(secret_key) or existing.get(env_key) or rand()

kc_admin_pw = sec.get("keycloak_admin_password") or existing.get("KEYCLOAK_ADMIN_PASSWORD") or rand()
kc_db_pw    = sec.get("keycloak_db_password")    or existing.get("KEYCLOAK_DB_PASSWORD")    or rand()
sonar_db_pw = sec.get("sonar_db_password")       or existing.get("SONAR_DB_PASSWORD")       or rand()
ta_secret   = sec.get("tinyauth_secret")         or existing.get("TINYAUTH_SECRET")         or secrets.token_hex(16)
client_sec  = sec.get("tinyauth_client_secret")  or existing.get("GENERIC_CLIENT_SECRET")   or secrets.token_hex(24)
demo_pw     = sec.get("demo_password")           or existing.get("_DEMO_PASSWORD")          or rand(14)

tls_port = st["tls_port"]
app, auth, kc_host = hosts["app"], hosts["auth"], hosts["keycloak"]
realm = kc["realm"]; client_id = kc["client_id"]

# --- .env ---------------------------------------------------------------
env = f"""# Generated by scripts/render.sh from {os.path.basename(cfg_path)} — do not commit.
COMPOSE_NET_NAME=sonar-stack
NET_SUBNET={st["net_subnet"]}
TRAEFIK_IP={st["traefik_ip"]}
BIND_ADDR={st["bind_addr"]}
TLS_PORT={tls_port}
APP_HOST={app}
AUTH_HOST={auth}
KEYCLOAK_HOST={kc_host}
KEYCLOAK_REALM={realm}
TLS_DIR={st["tls_dir"]}
DOCKER_SOCKET={st["docker_socket"]}
KEYCLOAK_ADMIN_USER={kc.get("admin_user","admin")}
KEYCLOAK_ADMIN_PASSWORD={kc_admin_pw}
KEYCLOAK_DB_PASSWORD={kc_db_pw}
TINYAUTH_SECRET={ta_secret}
SONAR_DB_PASSWORD={sonar_db_pw}
# demo user password (for the realm import); not consumed by compose.
_DEMO_PASSWORD={demo_pw}
"""
with open(env_path, "w") as f:
    f.write(env)
os.chmod(env_path, 0o600)

# --- tinyauth.env -------------------------------------------------------
with open(ta_path, "w") as f:
    f.write(f"GENERIC_CLIENT_ID={client_id}\nGENERIC_CLIENT_SECRET={client_sec}\n")
os.chmod(ta_path, 0o600)

# --- Keycloak realm -----------------------------------------------------
groups = {}
for u in kc.get("users", []):
    for g in u.get("groups", []):
        groups.setdefault(g, True)
group_role = {"sonar-admins": "sonar-admin", "sonar-users": "sonar-user"}
realm_json = {
    "realm": realm, "enabled": True, "sslRequired": "external",
    "registrationAllowed": False, "loginWithEmailAllowed": True,
    "roles": {"realm": [
        {"name": "sonar-admin", "description": "SonarQube administrators"},
        {"name": "sonar-user", "description": "SonarQube users"},
    ]},
    "groups": [
        {"name": g, "realmRoles": [group_role.get(g, "sonar-user")]} for g in groups
    ] or [{"name": "sonar-users", "realmRoles": ["sonar-user"]}],
    "users": [
        {
            "username": u["username"], "enabled": True, "emailVerified": True,
            "email": u.get("email", ""), "firstName": u.get("first_name", ""),
            "lastName": u.get("last_name", ""),
            "credentials": [{"type": "password", "value": demo_pw, "temporary": False}]
                if u["username"] == "demo" else [],
            "groups": ["/" + g for g in u.get("groups", [])],
        } for u in kc.get("users", [])
    ],
    "clients": [{
        "clientId": client_id, "name": "SonarQube SSO gateway (tinyauth)",
        "enabled": True, "protocol": "openid-connect", "publicClient": False,
        "secret": client_sec, "standardFlowEnabled": True,
        "directAccessGrantsEnabled": False, "serviceAccountsEnabled": False,
        "redirectUris": [f"https://{auth}:{tls_port}/api/oauth/callback/generic"],
        "webOrigins": ["+"], "defaultClientScopes": ["email", "profile", "roles"],
        "protocolMappers": [{
            "name": "groups", "protocol": "openid-connect",
            "protocolMapper": "oidc-group-membership-mapper",
            "config": {"claim.name": "groups", "full.path": "false",
                       "id.token.claim": "true", "access.token.claim": "true",
                       "userinfo.token.claim": "true"},
        }],
    }],
}
realm_out = os.path.join(stack_dir, "keycloak", "realm-sonar.json")
with open(realm_out, "w") as f:
    json.dump(realm_json, f, indent=2)

print("rendered:")
print("  .env")
print("  tinyauth.env")
print("  keycloak/realm-sonar.json")
print(f"demo user password: {demo_pw}")
PY
