FROM spark-maven-template:4.1.2-hadoop3

ENV SPARK_APPLICATION_JAR_NAME Docker-Maven-Template-0.1.0-SNAPSHOT
ENV SPARK_APPLICATION_MAIN_CLASS eu.bde.template.maven.WordCount
ENV SPARK_APPLICATION_ARGS "/spark/README.md"