---
scylla_image: docker.io/scylladb/scylla:2026.1.7
scylla_cluster_name: telemetry-cluster
scylla_node_count: 3
scylla_seed: scylla-node1
scylla_smp: 1
scylla_memory: 1G
scylla_overprovisioned: 1
scylla_developer_mode: 1
scylla_data_dir: /var/lib/scylla-nodes
scylla_schema_src: telemetry.cql
scylla_keyspace: telemetry
scylla_network: scylla
