#!/bin/sh
# UAT / smoke test for the WireGuard site-to-site stack. Real kernel WireGuard:
# two gateways complete a handshake and pass traffic across the encrypted
# tunnel, including reaching a service on the far gateway's tunnel address.
#
#   ./run-uat.sh           # bring up, assert, leave running
#   ./run-uat.sh --down    # tear down and drop generated state
#
# WireGuard needs the host `wireguard` kernel module. If it is not already
# loaded, this script loads it with sudo (prompting you) and unloads it again on
# --down, leaving the host as it was.
set -u

cd "$(dirname "$0")"
. ../../ci/net-uat-lib.sh

STACK=wireguard
COMPOSE_FILE=../docker-compose.yml
WG_IMG=docker.io/library/alpine:3.24
RUNTIME="${RUNTIME:-podman}"   # needed by wgkeys before net_init runs

# ensure_wg_available — the host must have WireGuard support. Creating a
# `type wireguard` interface auto-loads the kernel module (no modprobe / sudo
# needed), so we only check the module is available.
ensure_wg_available() {
    lsmod 2>/dev/null | grep -q '^wireguard' && return 0
    modinfo wireguard >/dev/null 2>&1 && return 0
    say "!! this host has no WireGuard kernel support (module 'wireguard' not"
    say "   found). Install it, or use the tailscale stack (userspace) instead."
    return 1
}

# unload_wg_module — best-effort restore: the tunnel auto-loaded the module;
# unload it if passwordless sudo is available (never prompts, never fails).
unload_wg_module() {
    lsmod 2>/dev/null | grep -q '^wireguard' || return 0
    sudo -n modprobe -r wireguard 2>/dev/null || true
}

if [ "${1:-}" = "--down" ]; then
    net_down
    rm -rf wg
    unload_wg_module
    exit 0
fi

# wgkeys — print "<private> <public>".
wgkeys() {
    $RUNTIME run --rm "$WG_IMG" sh -c \
        'apk add -q wireguard-tools >/dev/null 2>&1; p=$(wg genkey); printf "%s %s" "$p" "$(printf %s "$p" | wg pubkey)"'
}

say "== WireGuard site-to-site UAT (kernel tunnel handshake + traffic)"

ensure_wg_available || exit 1

# Generate both peer keypairs and render the two configs.
mkdir -p wg
set -- $(wgkeys); A_PRIV="$1"; A_PUB="$2"
set -- $(wgkeys); B_PRIV="$1"; B_PUB="$2"

cat > wg/wg-a.conf <<EOF
[Interface]
PrivateKey = $A_PRIV
ListenPort = 51820

[Peer]
PublicKey = $B_PUB
AllowedIPs = 10.9.0.2/32, 10.55.0.0/24
Endpoint = wg-b:51820
PersistentKeepalive = 15
EOF

cat > wg/wg-b.conf <<EOF
[Interface]
PrivateKey = $B_PRIV
ListenPort = 51820

[Peer]
PublicKey = $A_PUB
AllowedIPs = 10.9.0.1/32
EOF
chmod 644 wg/wg-a.conf wg/wg-b.conf

cat > .env <<EOF
# Generated by run-uat.sh — not for production use.
WG_IMAGE=$WG_IMG
TRANSIT_SUBNET=172.31.30.0/24
SITE_A_ADDR=10.9.0.1/24
SITE_B_ADDR=10.9.0.2/24
SITE_B_NETWORKS=10.55.0.0/24
COMPOSE_NET_NAME=${STACK}-net-uat
WG_DIR=$(pwd)/wg
EOF

net_init

say "-- bringing up the two gateways"
up wg-b wg-a || { net_down; exit 1; }
ensure_running wg-b
ensure_running wg-a

# Wait for the handshake to complete (non-zero latest-handshake on wg-a).
_i=0; while [ "$_i" -lt 40 ]; do
    _hs="$($RUNTIME exec wg-a wg show wg0 latest-handshakes 2>/dev/null | awk '{print $2}')"
    [ -n "${_hs:-}" ] && [ "${_hs:-0}" -gt 0 ] 2>/dev/null && break
    # Nudge the tunnel so the handshake initiates.
    $RUNTIME exec wg-a ping -c1 -W1 10.9.0.2 >/dev/null 2>&1 || true
    _i=$((_i+3)); sleep 3
done

say "== checks"

# 1. Interface up on both ends.
$RUNTIME exec wg-a ip link show wg0 >/dev/null 2>&1 \
    && pass "site-a brought up the kernel wg interface" \
    || { fail "site-a brought up the kernel wg interface" "$($RUNTIME logs --tail 5 wg-a 2>&1 | tr '\n' ' ')"; }
$RUNTIME exec wg-b ip link show wg0 >/dev/null 2>&1 \
    && pass "site-b brought up the kernel wg interface" \
    || fail "site-b brought up the kernel wg interface" ""

# 2. Handshake completed.
_hs="$($RUNTIME exec wg-a wg show wg0 latest-handshakes 2>/dev/null | awk '{print $2}')"
[ "${_hs:-0}" -gt 0 ] 2>/dev/null \
    && pass "handshake completed between the gateways" "$_hs" \
    || fail "handshake completed between the gateways" "no handshake"

# 3. Traffic across the tunnel.
if $RUNTIME exec wg-a ping -c3 -W2 10.9.0.2 >/dev/null 2>&1; then
    pass "site-a reaches site-b across the tunnel (ping)"
else
    fail "site-a reaches site-b across the tunnel (ping)" "100% loss"
fi

# 4. Encrypted bytes actually traversed the tunnel.
_tx="$($RUNTIME exec wg-a wg show wg0 transfer 2>/dev/null | awk '{print $2+$3}')"
[ "${_tx:-0}" -gt 0 ] 2>/dev/null \
    && pass "encrypted data traversed the tunnel (transfer counters)" \
    || fail "encrypted data traversed the tunnel (transfer counters)" "0 bytes"

# 5. Reach a service on the far side over the tunnel (site-to-site service).
_body="$($RUNTIME exec wg-a wget -qO- --timeout=5 http://10.9.0.2/marker 2>/dev/null)"
[ "$_body" = "reached-over-wg-tunnel" ] \
    && pass "service on the far gateway is reachable over the tunnel" \
    || fail "service on the far gateway is reachable over the tunnel" "got '$_body'"

if net_report; then
    say ""
    say "Tunnel:    wg-a 10.9.0.1  <->  wg-b 10.9.0.2   (podman exec wg-a wg show)"
    say "Tear down: ./run-uat.sh --down"
fi
net_report
