#!/bin/sh
# UAT / smoke test for the self-hosted Tailscale stack. A fully offline tailnet:
# headscale is the control server, two tailscale nodes (userspace/netstack — no
# tun, no kernel module, no host mutation) register with it, and we assert real
# tailnet connectivity plus subnet-router / exit-node advertisement.
#
#   ./run-uat.sh           # bring up, assert, leave running
#   ./run-uat.sh --down    # tear down and drop generated state
set -u

cd "$(dirname "$0")"
. ../../ci/net-uat-lib.sh

STACK=tailscale
COMPOSE_FILE=../docker-compose.yml
HS_IP=172.30.9.2

if [ "${1:-}" = "--down" ]; then
    net_down
    exit 0
fi

# hs <args...> — run the headscale CLI in the control container.
hs() { $RUNTIME exec headscale headscale "$@"; }
# node_ip4 <container> — the node's tailnet IPv4, or empty.
node_ip4() { $RUNTIME exec "$1" tailscale ip -4 2>/dev/null | grep -E '^100\.' | sed -n 1p; }

say "== Tailscale self-hosted UAT (headscale control + offline tailnet)"

cat > .env <<EOF
# Generated by run-uat.sh — not for production use.
HEADSCALE_IMAGE=docker.io/headscale/headscale:v0.29.2
TAILSCALE_IMAGE=docker.io/tailscale/tailscale:v1.98.9
BIND_ADDR=127.0.0.1
HS_PORT=8080
HS_IP=$HS_IP
NET_SUBNET=172.30.9.0/24
ADVERTISE_ROUTES=10.55.0.0/24
COMPOSE_NET_NAME=${STACK}-net-uat
HS_VOLUME=${STACK}-net-uat-hsdata
TS_AUTHKEY=
EOF

net_init

say "-- stage 1: headscale control server"
up headscale || { net_down; exit 1; }
ensure_running headscale
# headscale is ready when its CLI can talk to the daemon.
_i=0; while [ "$_i" -lt 40 ]; do hs users list >/dev/null 2>&1 && break; _i=$((_i+3)); sleep 3; done
if ! hs users list >/dev/null 2>&1; then
    say "!! headscale did not become ready"; dumplog headscale; net_report; exit 1
fi
pass "headscale control server is up"

say "-- stage 2: user + pre-auth key"
hs users create uatuser >/dev/null 2>&1 || true
_uid="$(hs users list -o json 2>/dev/null | python3 -c 'import sys,json;print(json.load(sys.stdin)[0]["id"])' 2>/dev/null)"
AUTHKEY="$(hs preauthkeys create --user "$_uid" --reusable --expiration 1h -o json 2>/dev/null \
    | python3 -c 'import sys,json;print(json.load(sys.stdin)["key"])' 2>/dev/null)"
if [ -n "$AUTHKEY" ]; then
    pass "headscale issued a pre-auth key"
else
    fail "headscale issued a pre-auth key" "empty"; net_report; exit 1
fi
# Feed the key to the node services.
sed -i "s#^TS_AUTHKEY=.*#TS_AUTHKEY=$AUTHKEY#" .env

say "-- stage 3: two tailnet nodes (userspace)"
up node-a node-b || { net_down; exit 1; }
ensure_running ts-node-a
ensure_running ts-node-b
# Wait for both nodes to obtain a 100.64.x address.
_i=0; while [ "$_i" -lt 60 ]; do
    [ -n "$(node_ip4 ts-node-a)" ] && [ -n "$(node_ip4 ts-node-b)" ] && break
    _i=$((_i+3)); sleep 3
done

say "== checks"
_a="$(node_ip4 ts-node-a)"; _b="$(node_ip4 ts-node-b)"
[ -n "$_a" ] && pass "node-a joined the tailnet" "$_a" || { fail "node-a joined the tailnet" "no IP"; dumplog ts-node-a; }
[ -n "$_b" ] && pass "node-b joined the tailnet" "$_b" || { fail "node-b joined the tailnet" "no IP"; dumplog ts-node-b; }

# Real tailnet data path: disco ping node-a -> node-b.
if [ -n "$_b" ] && $RUNTIME exec ts-node-a tailscale ping --timeout 8s node-b 2>&1 | grep -q '^pong'; then
    pass "node-a reaches node-b over the tailnet" "pong"
else
    fail "node-a reaches node-b over the tailnet" "no pong"
fi

# Both nodes registered on the control server.
_n="$(hs nodes list -o json 2>/dev/null | python3 -c 'import sys,json;print(len(json.load(sys.stdin)))' 2>/dev/null)"
[ "${_n:-0}" -ge 2 ] && pass "headscale shows both nodes registered" "$_n" \
    || fail "headscale shows both nodes registered" "got ${_n:-0}"

# Subnet route (site-to-site) + exit node advertised by the gateway node.
_routes="$(hs nodes list-routes 2>/dev/null)"
printf '%s' "$_routes" | grep -q '10.55.0.0/24' \
    && pass "gateway advertises the site-to-site subnet route" \
    || fail "gateway advertises the site-to-site subnet route" "not advertised"
printf '%s' "$_routes" | grep -q '0.0.0.0/0' \
    && pass "gateway advertises an exit node (egress route)" \
    || fail "gateway advertises an exit node (egress route)" "not advertised"

if net_report; then
    say ""
    say "Control:   http://127.0.0.1:8080   (podman exec headscale headscale nodes list)"
    say "Tailnet:   node-a $_a  <->  node-b $_b"
    say "Tear down: ./run-uat.sh --down"
fi
net_report
