#!/bin/sh
# UAT / smoke test for the CoreDNS secure-resolver stack. Real end-to-end DNS:
# an internal name resolves to its configured record, an external name resolves
# through the DoT upstream, a query from outside the ACL is REFUSED, and the
# DNS-over-TLS listener answers over a certificate the client verifies.
#
#   ./run-uat.sh           # bring up, assert, leave running
#   ./run-uat.sh --down    # tear down and drop generated state
#
# Needs outbound DoT (853/tcp to Quad9) for the upstream-resolution check.
set -u

cd "$(dirname "$0")"
. ../../ci/net-uat-lib.sh

STACK=coredns
COMPOSE_FILE=../docker-compose.yml
CERT_CN=dns.local

if [ "${1:-}" = "--down" ]; then
    net_down
    exit 0
fi

# dig_status <container> <query> — grep the DNS rcode from a dig answer.
dig_status() {
    $RUNTIME exec "$1" dig +time=3 +tries=1 @coredns "$2" A 2>/dev/null \
        | sed -n 's/.*status: \([A-Z]*\),.*/\1/p' | sed -n 1p
}

# wait_tool <container> <bin> <seconds> — the alpine clients apk-add their tools
# at start; wait for them.
wait_tool() {
    _c="$1"; _b="$2"; _t="$3"; _i=0
    while [ "$_i" -lt "$_t" ]; do
        $RUNTIME exec "$_c" sh -c "command -v $_b" >/dev/null 2>&1 && return 0
        _i=$((_i + 3)); sleep 3
    done
    say "!! $_b never appeared in $_c"; return 1
}

say "== CoreDNS secure-resolver UAT (DoT upstream + ACL + DoT listener)"

cat > .env <<EOF
# Generated by run-uat.sh — not for production use.
DNS_IMAGE=docker.io/coredns/coredns:1.13.1
BIND_ADDR=127.0.0.1
DNS_PORT=1053
DOT_PORT=1853
TLS_DIR=$(pwd)/tls
NET_ALLOWED=${STACK}-uat-allowed
NET_DENIED=${STACK}-uat-denied
EOF

net_init

say "-- bringing up resolver + clients (alpine clients install dig/kdig)"
up coredns dig-allowed dig-denied || { net_down; exit 1; }
ensure_running coredns
wait_tool dig-allowed dig 150 || { net_report; exit 1; }
wait_tool dig-allowed kdig 150 || { net_report; exit 1; }
wait_tool dig-denied dig 150 || { net_report; exit 1; }

# Wait for the resolver to actually answer the internal name.
_i=0
while [ "$_i" -lt 60 ]; do
    [ "$($RUNTIME exec dig-allowed dig +short +time=2 +tries=1 @coredns backend.svc.internal A 2>/dev/null)" = "10.0.50.20" ] && break
    _i=$((_i + 3)); sleep 3
done

say "== checks"

# 1. Internal (authoritative) name.
_ans="$($RUNTIME exec dig-allowed dig +short +time=3 +tries=1 @coredns backend.svc.internal A 2>/dev/null | sed -n 1p)"
[ "$_ans" = "10.0.50.20" ] \
    && pass "internal name resolves to its record" "$_ans" \
    || fail "internal name resolves to its record" "got '$_ans'"

# 2. External name via the DoT upstream (answer returned => DoT path works).
_ext="$($RUNTIME exec dig-allowed dig +noall +answer +time=5 +tries=2 @coredns example.com A 2>/dev/null | grep -c 'IN')"
[ "${_ext:-0}" -ge 1 ] \
    && pass "external name resolves through DoT upstream" "$_ext answer(s)" \
    || fail "external name resolves through DoT upstream" "no answer"

# 3. ACL: a source outside acl_allow is REFUSED.
_st="$(dig_status dig-denied example.com)"
[ "$_st" = "REFUSED" ] \
    && pass "query from outside the ACL is REFUSED" "$_st" \
    || fail "query from outside the ACL is REFUSED" "got '$_st'"

# 3b. ...and the allowed source is NOT refused.
_sta="$(dig_status dig-allowed example.com)"
[ "$_sta" = "NOERROR" ] \
    && pass "query from an allowed source is served" "$_sta" \
    || fail "query from an allowed source is served" "got '$_sta'"

# 4. DoT listener: kdig over TLS, verifying the cert against the UAT CA.
_dot="$($RUNTIME exec dig-allowed kdig +tls +tls-ca=/tls/ca.crt +tls-hostname=dns.local \
    +short @coredns -p 853 backend.svc.internal A 2>/dev/null | sed -n 1p)"
[ "$_dot" = "10.0.50.20" ] \
    && pass "DoT listener answers over a verified TLS cert" "$_dot" \
    || fail "DoT listener answers over a verified TLS cert" "got '$_dot'"

if net_report; then
    say ""
    say "Resolver:  dig @127.0.0.1 -p 1053 backend.svc.internal"
    say "DoT:       kdig +tls @127.0.0.1 -p 1853 backend.svc.internal"
    say "Tear down: ./run-uat.sh --down"
fi
net_report
