#!/bin/sh
# UAT / smoke test for the Traefik reverse-proxy stack. Proves the proxy
# terminates TLS with the local CA and forwards a real request through to the
# demo backend, that security headers are applied, and that an unknown Host
# gets no route (404).
#
#   ./run-uat.sh           # bring up, assert, leave running
#   ./run-uat.sh --down    # tear down and drop generated state
#
# No host entry is needed: curl's --resolve maps the vhost to 127.0.0.1.
set -u

cd "$(dirname "$0")"
. ../../ci/net-uat-lib.sh

STACK=traefik
COMPOSE_FILE=../docker-compose.yml
TLS_PORT=8443
APP_HOST=app.localhost
CERT_CN=$APP_HOST
CERT_SANS="whoami.localhost"

if [ "${1:-}" = "--down" ]; then
    net_down
    exit 0
fi

say "== Traefik reverse-proxy UAT (TLS termination + backend routing)"

# uat/.env drives the compose file.
cat > .env <<EOF
# Generated by run-uat.sh — not for production use.
PROXY_IMAGE=docker.io/traefik:v3.7
BIND_ADDR=127.0.0.1
TLS_PORT=$TLS_PORT
HTTP_PORT=8080
TLS_DIR=$(pwd)/tls
COMPOSE_NET_NAME=${STACK}-net-uat
EOF

net_init

APP="https://$APP_HOST:$TLS_PORT"
RESOLVE="--resolve $APP_HOST:$TLS_PORT:127.0.0.1"

say "-- bringing up proxy + demo backend"
up whoami traefik || { net_down; exit 1; }
ensure_running whoami-demo
ensure_running traefik-proxy
wait_healthy traefik-proxy 60 || { dumplog traefik-proxy; net_report; exit 1; }
wait_http "$APP/" 60 '^(200)$' --cacert "$CA" $RESOLVE || {
    dumplog traefik-proxy; net_report; exit 1; }

say "== checks"
check 200 "request reaches backend through TLS" --cacert "$CA" $RESOLVE "$APP/"
check_body "whoami-demo" "response body comes from the demo backend" \
    --cacert "$CA" $RESOLVE "$APP/"

# The backend echoes request headers; the proxy must add X-Forwarded-Proto.
check_body "X-Forwarded-Proto: https" "proxy sets X-Forwarded-Proto" \
    --cacert "$CA" $RESOLVE "$APP/"

# Security header applied by the secure-headers middleware.
_hdrs="$(curl -s -D - -o /dev/null -A "$UA" --cacert "$CA" $RESOLVE "$APP/")"
printf '%s' "$_hdrs" | grep -qi '^x-frame-options:' \
    && pass "secure-headers middleware applied" \
    || fail "secure-headers middleware applied" "no X-Frame-Options"

say "-- negative checks"
# HTTP is redirected to HTTPS (published on an unprivileged host port).
check 301 "plain HTTP is redirected to HTTPS" \
    --resolve "$APP_HOST:8080:127.0.0.1" "http://$APP_HOST:8080/"
# Unknown vhost has no router -> 404. -k: the point is routing, not the cert
# (the default cert legitimately does not match this SNI).
check 404 "unknown Host gets no route" \
    -k --resolve "nope.localhost:$TLS_PORT:127.0.0.1" \
    "https://nope.localhost:$TLS_PORT/"
# TLS is served by our CA (verification succeeds).
check 200 "certificate verifies against the UAT CA" --cacert "$CA" $RESOLVE "$APP/"

if net_report; then
    say ""
    say "Proxy:     $APP   (curl --cacert $(pwd)/tls/ca.crt --resolve $APP_HOST:$TLS_PORT:127.0.0.1 ...)"
    say "Tear down: ./run-uat.sh --down"
fi
net_report
