[opensearch]
os-node1 ansible_host=192.168.1.11
os-node2 ansible_host=192.168.1.12
os-node3 ansible_host=192.168.1.13

[opensearch:vars]
ansible_user=deploy
ansible_python_interpreter=/usr/bin/python3
