x-common-vars-apps: &common-vars-apps
  security_opt:
    - no-new-privileges:true
  restart: on-failure
  env_file:
    - ../.env
  networks:
    - elastic

services:
  logstash:
    <<: *common-vars-apps
    build:
      context: .
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    volumes:
      - certs:/usr/share/logstash/config/certs/:ro,z
    ports:
      - "5044:5044"
      - "50000:50000"
      - "5140:5140/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: -Xms512m -Xmx512m
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
      LOGSTASH_INTERNAL_PASSWORD: ${LOGSTASH_INTERNAL_PASSWORD:-}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --max-time 120 --retry 120 --retry-delay 1 --show-error --silent http://localhost:9600 | grep -q '\"status\":\"green\"'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

networks:
  elastic:
    external: true
    name: ${STACK_NETWORK:-elastic_elastic}

volumes:
  certs:
    external: true
    name: ${STACK_CERTS:-elastic_certs}
