log-pipeline:
  source:
    http:
      port: 2021
      path: "/logs/ingest"
  processor:
    - date:
        from_time_received: true
        destination: "@timestamp"
    - add_entries:
        entries:
          - key: "dataset"
            value: "generic"
            overwrite_if_key_exists: false
          - key: "namespace"
            value: "default"
            overwrite_if_key_exists: false
  sink:
    - opensearch:
        hosts: [ "https://opensearch-node1:9200" ]
        cert: "/usr/share/data-prepper/certs/root-ca.pem"
        username: "${OS_USER}"
        password: "${OS_PASS}"
        index: "logs-${dataset}-${namespace}"

otel-logs-pipeline:
  source:
    otel_logs_source:
      port: 21892
      ssl: false
  processor:
    - date:
        from_time_received: true
        destination: "@timestamp"
  sink:
    - opensearch:
        hosts: [ "https://opensearch-node1:9200" ]
        cert: "/usr/share/data-prepper/certs/root-ca.pem"
        username: "${OS_USER}"
        password: "${OS_PASS}"
        index: "logs-otel-default"
