# syntax=docker/dockerfile:1
# backstage: an open platform for building developer portals.
ARG repo="quay.io/almalinuxorg" \
    base_image="10-minimal" \
    image_hash="bec1954031f1655b66902589bee9b9a104fc66a3eeae9e924cf24efee6aa9a00"

FROM ${repo}/${base_image}@sha256:${image_hash}

RUN \
    microdnf install -y epel-release yum-utils; \
    /usr/bin/crb enable; \
    microdnf update -y; \
    \
    dnf module enable nodejs:18 -y; \
    \
    microdnf install -y \
        python3 \
        gcc \
        gcc-c++ \
        zlib-devel \
        brotli-devel \
        openssl-devel \
        libuv-devel \
        bash \
        git \
        nodejs \
        npm \
        wget; \
    \
    npm install -g npm@11.18.0; \
    npm install -g yarn; \
    echo "backstage" | npx --yes @backstage/create-app@latest; \
    \
    microdnf remove -y \
        gcc gcc-c++ zlib-devel brotli-devel openssl-devel libuv-devel; \
    /usr/bin/crb disable; \
    microdnf remove -y \
        epel-release yum-utils; \
    microdnf clean all; \
    rm -rf /var/cache/dnf /var/cache/yum /tmp/* /var/tmp/*; \
    truncate -s 0 /var/log/*log

EXPOSE 3000 7007
WORKDIR /backstage
RUN yarn add --cwd packages/backend pg
ENTRYPOINT [ "/bin/sh", "-c", "yarn dev" ]
