# Shared helpers for the devops stacks' SSO UAT harnesses.
# Sourced (not executed) by each <stack>/uat/run-uat.sh.
#
# Every stack follows the same shape: traefik terminates TLS, tinyauth
# answers traefik's forwardAuth, and the application is reachable only
# through traefik on an internal network. The UAT runs the same compose
# file that ansible deploys, driven by a generated uat/.env.
#
# A caller sets these before sourcing:
#   STACK        short stack name, e.g. grafana
#   TLS_PORT     host port traefik publishes on 127.0.0.1
#   APP_HOST     browser hostname for the application
#   AUTH_HOST    browser hostname for the tinyauth login UI
#   SAN_HOSTS    extra DNS names for the certificate (space separated, optional)
# and after sourcing calls: uat_init, then the check_* assertions, then
# uat_report.

PASS=0
FAIL=0

say() { printf '%s\n' "$*"; }

pass() { PASS=$((PASS + 1)); printf '  PASS  %-58s %s\n' "$1" "${2:-OK}"; }
fail() { FAIL=$((FAIL + 1)); printf '  FAIL  %-58s %s\n' "$1" "${2:-}"; }

# check <expected_code> <description> [curl args...]
check() {
    _want="$1"; _desc="$2"; shift 2
    _got="$(curl -s -o /dev/null -w '%{http_code}' --max-time 30 "$@")"
    [ "$_got" = "$_want" ] && pass "$_desc" "$_got" || fail "$_desc" "got $_got want $_want"
}

# check_any <expected_codes_regex> <description> [curl args...]
check_any() {
    _re="$1"; _desc="$2"; shift 2
    _got="$(curl -s -o /dev/null -w '%{http_code}' --max-time 30 "$@")"
    printf '%s' "$_got" | grep -qE "$_re" \
        && pass "$_desc" "$_got" || fail "$_desc" "got $_got want $_re"
}

# wait_http <url> <seconds> <accept-codes-regex> [curl args...]
wait_http() {
    _u="$1"; _t="$2"; _re="$3"; shift 3
    _i=0
    while [ "$_i" -lt "$_t" ]; do
        _code="$(curl -s -o /dev/null -w '%{http_code}' --max-time 10 "$@" "$_u" 2>/dev/null)"
        printf '%s' "$_code" | grep -qE "$_re" && return 0
        _i=$((_i + 3)); sleep 3
    done
    say "!! $_u not answering ($_re) after $_t s (last: ${_code:-none})"
    return 1
}

# wait_healthy <container> <seconds> — gate between bring-up stages.
wait_healthy() {
    _c="$1"; _t="${2:-180}"; _i=0
    while [ "$_i" -lt "$_t" ]; do
        _s="$($RUNTIME inspect -f '{{.State.Health.Status}}' "$_c" 2>/dev/null || echo missing)"
        [ "$_s" = "healthy" ] && return 0
        # A container with no healthcheck reports an empty status once running.
        if [ -z "$_s" ]; then
            [ "$($RUNTIME inspect -f '{{.State.Running}}' "$_c" 2>/dev/null)" = "true" ] && return 0
        fi
        _i=$((_i + 3)); sleep 3
    done
    say "!! $_c not healthy after $_t s (last: ${_s:-none})"
    return 1
}

# up <service...> — bring services up without recreating live containers.
# podman-compose recreates dependent chains when invoked broadly, so each
# stage names its services explicitly.
up() {
    $COMPOSE up -d --no-recreate "$@"
}

# ensure_running <container> — restart a container left stopped by a
# previous partial run (podman-compose cannot adopt those).
ensure_running() {
    _c="$1"
    [ "$($RUNTIME inspect -f '{{.State.Running}}' "$_c" 2>/dev/null)" = "true" ] && return 0
    $RUNTIME start "$_c" >/dev/null 2>&1 || true
}

# gen_tls — local CA plus one server certificate covering the stack hosts.
# The key is world readable: rootless podman maps container uids into the
# user namespace, so a 0600 host file is unreadable to nginx/traefik uids.
gen_tls() {
    [ -f tls/ca.crt ] && { chmod 644 tls/tls.key tls/tls.crt tls/ca.crt; return 0; }
    say "-- generating TLS CA + certs into uat/tls"
    mkdir -p tls
    openssl genrsa -out tls/ca.key 4096 2>/dev/null
    openssl req -x509 -new -nodes -key tls/ca.key -sha256 -days 3650 \
        -out tls/ca.crt -subj "/CN=$STACK UAT CA" 2>/dev/null
    _san="subjectAltName=DNS:$APP_HOST,DNS:$AUTH_HOST,DNS:localhost,IP:127.0.0.1"
    for _h in ${SAN_HOSTS:-}; do _san="$_san,DNS:$_h"; done
    openssl genrsa -out tls/tls.key 2048 2>/dev/null
    openssl req -new -key tls/tls.key -out tls/tls.csr \
        -subj "/CN=$APP_HOST" -addext "$_san" 2>/dev/null
    openssl x509 -req -in tls/tls.csr -CA tls/ca.crt -CAkey tls/ca.key \
        -CAcreateserial -out tls/tls.crt -days 365 -sha256 \
        -extfile /dev/stdin 2>/dev/null <<EOF
$_san
EOF
    chmod 644 tls/tls.key tls/tls.crt tls/ca.crt
}

# gen_env — write uat/.env with generated credentials. Extra stack specific
# lines come from the caller's uat_env_extra() if it defines one.
gen_env() {
    [ -f .env ] && return 0
    say "-- generating uat/.env credentials"
    UAT_USER="${UAT_USER:-uat-admin}"
    UAT_PW="$(openssl rand -base64 15 | tr -d '/+=')"
    {
        echo "# Generated by uat/run-uat.sh — not for production use."
        echo "COMPOSE_NET_NAME=${STACK}-sso-uat-net"
        echo "NET_SUBNET=$NET_SUBNET"
        echo "TRAEFIK_IP=$TRAEFIK_IP"
        echo "DOCKER_SOCKET=${DOCKER_SOCKET:-/var/run/docker.sock}"
        echo "TLS_DIR=$(pwd)/tls"
        echo "BIND_ADDR=127.0.0.1"
        echo "TLS_PORT=$TLS_PORT"
        echo "APP_HOST=$APP_HOST"
        echo "AUTH_HOST=$AUTH_HOST"
        echo "TINYAUTH_SECRET=$(openssl rand -hex 16)"
        echo "TINYAUTH_APP_URL=https://$AUTH_HOST:$TLS_PORT"
        echo "TINYAUTH_USERS=$(htpasswd -nbB "$UAT_USER" "$UAT_PW")"
        echo "SSO_USER=$UAT_USER"
        echo "SSO_EMAIL=$UAT_USER@example.com"
        echo "POSTGRES_PASSWORD=$(openssl rand -hex 16)"
        echo "ADMIN_PASSWORD=$(openssl rand -base64 15 | tr -d '/+=')"
        command -v uat_env_extra >/dev/null 2>&1 && uat_env_extra
    } > .env
    chmod 600 .env
    printf '%s' "$UAT_PW" > .uat-password
    chmod 600 .uat-password
}

# podman_socket — traefik's docker provider needs a runtime socket. Point it
# at the rootless podman socket when no docker socket exists.
podman_socket() {
    [ -S /var/run/docker.sock ] && return 0
    _sock="/run/user/$(id -u)/podman/podman.sock"
    [ -S "$_sock" ] || systemctl --user start podman.socket >/dev/null 2>&1 || true
    [ -S "$_sock" ] && export DOCKER_SOCKET="$_sock"
}

# uat_init — everything every stack needs before the first bring-up stage.
uat_init() {
    RUNTIME="${RUNTIME:-podman}"
    COMPOSE_BIN="${COMPOSE_BIN:-podman-compose}"
    COMPOSE="$COMPOSE_BIN -p ${STACK}-sso-uat --env-file .env -f ../sso/docker-compose.yml"
    CA=tls/ca.crt
    APP="https://$APP_HOST:$TLS_PORT"
    LOGIN="https://$AUTH_HOST:$TLS_PORT"
    UA="Mozilla/5.0 (X11; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0"
    gen_tls
    podman_socket
    gen_env
    UAT_PW="$(cat .uat-password 2>/dev/null)"
    UAT_USER="$(grep '^SSO_USER=' .env | cut -d= -f2)"
}

# uat_down — tear the project down and drop generated state.
uat_down() {
    RUNTIME="${RUNTIME:-podman}"
    COMPOSE_BIN="${COMPOSE_BIN:-podman-compose}"
    [ -f .env ] || : > .env
    $COMPOSE_BIN -p "${STACK}-sso-uat" --env-file .env -f ../sso/docker-compose.yml down -v
    rm -f .env .uat-password .sso-cookie
}

# sso_login — authenticate against tinyauth and stash the session cookie.
# tinyauth scopes its cookie to Domain=localhost, which covers both the app
# and login hostnames. curl's public suffix handling drops single label
# domains from its cookie jar, so the cookie is captured and replayed by
# hand; browsers keep it and need no such help.
sso_login() {
    SSO_COOKIE="$(curl -s --cacert "$CA" -A "$UA" -D - -H 'Content-Type: application/json' \
        -X POST "$LOGIN/api/login" \
        -d "{\"username\":\"$UAT_USER\",\"password\":\"$UAT_PW\"}" -o /dev/null \
        | grep -i '^set-cookie:' | sed -E 's/^set-cookie: ([^;]+);.*/\1/I' | sed -n 1p)"
    [ -n "$SSO_COOKIE" ]
}

# check_gate — the assertions every stack shares: the app is unreachable
# without a session, browsers are bounced to the tinyauth login UI, and the
# login UI itself serves over TLS.
check_gate() {
    check 401 "app rejects unauthenticated API request" --cacert "$CA" "$APP/"
    check 307 "app redirects browser to SSO login"      --cacert "$CA" -A "$UA" -H 'Accept: text/html' "$APP/"
    check 200 "tinyauth login UI over TLS"              -L --cacert "$CA" -A "$UA" "$LOGIN/"
    _loc="$(curl -s -o /dev/null -w '%{redirect_url}' --max-time 30 --cacert "$CA" \
        -A "$UA" -H 'Accept: text/html' "$APP/")"
    case "$_loc" in
        *"$AUTH_HOST:$TLS_PORT/login"*redirect_uri*)
            pass "redirect targets login UI with return URL" ;;
        *)  fail "redirect targets login UI with return URL" "$_loc" ;;
    esac
}

# check_spoof <header> — a client supplied identity header must not reach
# the application. traefik overwrites the forwardAuth response headers, so
# an unauthenticated request carrying one is still rejected.
check_spoof() {
    check 401 "spoofed $1 header is rejected" --cacert "$CA" -H "$1: attacker" "$APP/"
}

# uat_report — print the tally and, on success, how to reach the stack.
uat_report() {
    say ""
    say "== result: $PASS passed, $FAIL failed"
    if [ "$FAIL" -eq 0 ]; then
        say ""
        say "Application:  $APP"
        say "Login UI:     $LOGIN   ($UAT_USER / $UAT_PW)"
        say "  Trust $(pwd)/tls/ca.crt in your browser, or accept the warning."
        say "Tear down:    ./run-uat.sh --down"
    fi
    [ "$FAIL" -eq 0 ]
}
