#!/bin/sh
# Render the stack's compose artifacts from stack.yaml:
#   .env                        compose environment (chmod 600)
#   keycloak/realm-neo4j.json   imported realm (realm, OIDC client, demo user)
#
# Blank secrets in stack.yaml are generated once and persisted to .env
# (gitignored); re-runs reuse them. TLS material is not generated here — supply
# real certificates in stack.tls_dir for production (the UAT harness generates a
# local CA for testing).
#
#   scripts/render.sh [path/to/stack.yaml]
set -eu

HERE="$(cd "$(dirname "$0")" && pwd)"
STACK_DIR="$(cd "$HERE/.." && pwd)"
CONFIG="${1:-$STACK_DIR/stack.yaml}"

command -v python3 >/dev/null 2>&1 || { echo "!! python3 required" >&2; exit 1; }

STACK_DIR="$STACK_DIR" CONFIG="$CONFIG" python3 - <<'PY'
import os, secrets, string, sys
try:
    import yaml
except ImportError:
    sys.exit("!! python3 yaml (PyYAML) required")

stack_dir = os.environ["STACK_DIR"]
with open(os.environ["CONFIG"]) as f:
    cfg = yaml.safe_load(f)

st = cfg["stack"]; hosts = cfg["hosts"]; kc = cfg["keycloak"]
models = cfg.get("models", {}); sec = cfg.get("secrets") or {}

def rand(n=24):
    a = string.ascii_letters + string.digits
    return "".join(secrets.choice(a) for _ in range(n))

# Reuse secrets already written to .env for idempotency.
env_path = os.path.join(stack_dir, ".env")
existing = {}
if os.path.exists(env_path):
    for line in open(env_path):
        if "=" in line and not line.startswith("#"):
            k, v = line.rstrip("\n").split("=", 1); existing[k] = v

def want(cfg_key, env_key, gen=rand):
    return sec.get(cfg_key) or existing.get(env_key) or gen()

kc_admin_pw = want("keycloak_admin_password", "KEYCLOAK_ADMIN_PASSWORD")
kc_db_pw    = want("keycloak_db_password", "KEYCLOAK_DB_PASSWORD", lambda: secrets.token_hex(20))
ow_db_pw    = want("openwebui_db_password", "OPENWEBUI_DB_PASSWORD", lambda: secrets.token_hex(20))
webui_key   = want("webui_secret_key", "WEBUI_SECRET_KEY", lambda: secrets.token_hex(32))
client_sec  = want("oauth_client_secret", "OAUTH_CLIENT_SECRET", lambda: secrets.token_hex(24))
neo4j_pw    = want("neo4j_password", "NEO4J_PASSWORD", lambda: secrets.token_hex(16))
graphrag_key = want("graphrag_api_key", "GRAPHRAG_API_KEY", lambda: secrets.token_hex(24))
demo_pw     = want("demo_password", "_DEMO_PASSWORD", lambda: rand(14))

tls_port = st["tls_port"]
app, kc_host = hosts["app"], hosts["keycloak"]
realm = kc["realm"]; client_id = kc["client_id"]

env = f"""# Generated by scripts/render.sh from {os.path.basename(os.environ["CONFIG"])} — do not commit.
COMPOSE_NET_NAME=neo4j-stack
NET_SUBNET={st["net_subnet"]}
TRAEFIK_IP={st["traefik_ip"]}
BIND_ADDR={st["bind_addr"]}
TLS_PORT={tls_port}
TLS_DIR={st["tls_dir"]}
DOCKER_SOCKET={st["docker_socket"]}
APP_HOST={app}
KEYCLOAK_HOST={kc_host}
KEYCLOAK_REALM={realm}
KEYCLOAK_ADMIN_USER={kc.get("admin_user","admin")}
KEYCLOAK_ADMIN_PASSWORD={kc_admin_pw}
KEYCLOAK_DB_PASSWORD={kc_db_pw}
OPENWEBUI_DB_PASSWORD={ow_db_pw}
WEBUI_SECRET_KEY={webui_key}
OAUTH_CLIENT_ID={client_id}
OAUTH_CLIENT_SECRET={client_sec}
NEO4J_USERNAME=neo4j
NEO4J_PASSWORD={neo4j_pw}
GRAPHRAG_API_KEY={graphrag_key}
LLM={models.get("llm","llama3.2:3b")}
EMBEDDING_MODEL={models.get("embedding_model","sentence_transformer")}
RAG_SEARCH_TYPE={models.get("rag_search_type","vector")}
RAG_USE_COMPRESSION={models.get("rag_use_compression","false")}
# demo user password (for the realm import); not consumed by compose.
_DEMO_PASSWORD={demo_pw}
"""
with open(env_path, "w") as f:
    f.write(env)
os.chmod(env_path, 0o600)

# --- Keycloak realm from the template -----------------------------------
demo = (kc.get("users") or [{}])[0]
tmpl = open(os.path.join(stack_dir, "keycloak", "realm-neo4j.json.tmpl")).read()
subs = {
    "@REALM@": realm,
    "@CLIENT_ID@": client_id,
    "@CLIENT_SECRET@": client_sec,
    "@REDIRECT_URI@": f"https://{app}:{tls_port}/oauth/oidc/callback",
    "@DEMO_USER@": demo.get("username", "demo"),
    "@DEMO_EMAIL@": demo.get("email", "demo@example.com"),
    "@DEMO_PASSWORD@": demo_pw,
}
for k, v in subs.items():
    tmpl = tmpl.replace(k, v)
with open(os.path.join(stack_dir, "keycloak", "realm-neo4j.json"), "w") as f:
    f.write(tmpl)

print("rendered:")
print("  .env")
print("  keycloak/realm-neo4j.json")
print(f"demo user password: {demo_pw}")
PY
