outputs:
  out_demo_fs:
    type: filesystem
    destPath: /opt/cribl/demo-output
    format: json
    compress: none
    maxFileSizeMB: 32
    maxFileOpenTimeSec: 10
    maxFileIdleTimeSec: 5
    partitionExpr: "`${host}`"
