#!/bin/sh
# UAT for the HashiCorp-stack remote-access layer. Proves a workstation on the
# "internet" reaches ONLY the brokered Boundary controller through the bastion
# tunnel, and can reach nothing else on the internal network — the no-exfil
# posture. Fully offline (self-hosted headscale, userspace tailnet, no kernel
# module, no host mutation).
#
#   ./run-uat.sh           # bring up, assert, leave running
#   ./run-uat.sh --down    # tear down and drop generated state
set -u

cd "$(dirname "$0")"
. ../../../../ci/net-uat-lib.sh

STACK=acc
COMPOSE_FILE=./docker-compose.yml
PROJECT=acc-uat

hs() { $RUNTIME exec acc-headscale headscale "$@"; }
# ws_curl <curl-args...> — run curl from the workstation helper, which shares
# the endpoint node's netns (and its tailscale SOCKS5 proxy).
ws_curl() {
    $RUNTIME exec acc-workstation sh -c "curl -s --max-time 8 $*"
}

if [ "${1:-}" = "--down" ]; then
    net_down
    exit 0
fi

say "== HashiCorp access UAT (workstation -> tunnel -> bastion -> Boundary only)"

cat > .env <<EOF
# Generated by run-uat.sh — not for production use.
HEADSCALE_IMAGE=docker.io/headscale/headscale:v0.29.2
TAILSCALE_IMAGE=docker.io/tailscale/tailscale:v1.98.9
COREDNS_IMAGE=docker.io/coredns/coredns:1.13.1
BROKER_IMAGE=docker.io/library/alpine:3.24
WAN_NET=${PROJECT}-wan
LAN_NET=${PROJECT}-lan
HS_VOLUME=${PROJECT}-hsdata
BASTION_AUTHKEY=
ENDPOINT_AUTHKEY=
EOF

net_init

say "-- stage 1: control plane (headscale + deny-by-default policy)"
up headscale || { net_down; exit 1; }
ensure_running acc-headscale
ensure_stable acc-headscale 8 || { net_report; exit 1; }
_i=0; while [ "$_i" -lt 40 ]; do hs users list >/dev/null 2>&1 && break; _i=$((_i+3)); sleep 3; done
hs users list >/dev/null 2>&1 || { say "!! headscale not ready"; dumplog acc-headscale; net_report; exit 1; }
pass "headscale control plane is up"

hs users create bastion >/dev/null 2>&1 || true
hs users create endpoint >/dev/null 2>&1 || true
_bid="$(hs users list -o json 2>/dev/null | python3 -c 'import sys,json;print([u["id"] for u in json.load(sys.stdin) if u["name"]=="bastion"][0])' 2>/dev/null)"
_eid="$(hs users list -o json 2>/dev/null | python3 -c 'import sys,json;print([u["id"] for u in json.load(sys.stdin) if u["name"]=="endpoint"][0])' 2>/dev/null)"
BKEY="$(hs preauthkeys create --user "$_bid" --reusable --expiration 1h -o json 2>/dev/null | python3 -c 'import sys,json;print(json.load(sys.stdin)["key"])' 2>/dev/null)"
EKEY="$(hs preauthkeys create --user "$_eid" --reusable --expiration 1h -o json 2>/dev/null | python3 -c 'import sys,json;print(json.load(sys.stdin)["key"])' 2>/dev/null)"
[ -n "$BKEY" ] && [ -n "$EKEY" ] && pass "headscale issued bastion + workstation keys" \
    || { fail "headscale issued keys" "empty"; net_report; exit 1; }
sed -i "s#^BASTION_AUTHKEY=.*#BASTION_AUTHKEY=$BKEY#;s#^ENDPOINT_AUTHKEY=.*#ENDPOINT_AUTHKEY=$EKEY#" .env

say "-- stage 2: internal segment + bastion + workstation"
up boundary internaldb coredns bastion-ts broker endpoint-ts workstation || { net_down; exit 1; }
for c in acc-boundary acc-internaldb acc-coredns acc-bastion-ts acc-broker acc-endpoint-ts acc-workstation; do ensure_running "$c"; done
ensure_stable acc-bastion-ts 8 || { net_report; exit 1; }
ensure_stable acc-endpoint-ts 8 || { net_report; exit 1; }

# Wait for both nodes to obtain tailnet addresses.
_i=0; while [ "$_i" -lt 60 ]; do
    _bip="$($RUNTIME exec acc-bastion-ts tailscale ip -4 2>/dev/null | grep '^100\.')"
    _eip="$($RUNTIME exec acc-endpoint-ts tailscale ip -4 2>/dev/null | grep '^100\.')"
    [ -n "$_bip" ] && [ -n "$_eip" ] && break
    _i=$((_i+3)); sleep 3
done
[ -n "$_bip" ] && [ -n "$_eip" ] && pass "bastion + workstation joined the tailnet" "bastion=$_bip" \
    || { fail "nodes joined the tailnet" "bastion='$_bip' ws='$_eip'"; dumplog acc-bastion-ts; net_report; exit 1; }

say "== checks: authorized path"
# The workstation reaches Boundary via the broker over the tunnel. Retry briefly
# while the broker socat + Boundary mock finish coming up.
_i=0; _body=""
while [ "$_i" -lt 30 ]; do
    _body="$(ws_curl "--socks5-hostname 127.0.0.1:1055 http://$_bip:9200/")"
    printf '%s' "$_body" | grep -q 'boundary-controller' && break
    _i=$((_i+3)); sleep 3
done
printf '%s' "$_body" | grep -q 'boundary-controller' \
    && pass "workstation reaches Boundary through the bastion tunnel" \
    || fail "workstation reaches Boundary through the bastion tunnel" "$(printf '%s' "$_body" | head -c 80)"

say "== checks: no exfiltration (everything else denied)"
# 1. An internal service that is NOT brokered has no route at all.
_r="$(ws_curl "--socks5-hostname 127.0.0.1:1055 http://172.30.77.20:5432/")"
[ -z "$_r" ] && pass "internal database is unreachable (no route to internal net)" \
    || fail "internal database is unreachable" "leaked: $(printf '%s' "$_r" | head -c 60)"

# 2. A port the bastion IS listening on but the policy does NOT allow (2222):
#    proves the ACL denies it, not merely that nothing is listening.
_r="$(ws_curl "--socks5-hostname 127.0.0.1:1055 http://$_bip:2222/")"
[ -z "$_r" ] && pass "non-allowed bastion port is blocked by the ACL" \
    || fail "non-allowed bastion port is blocked by the ACL" "leaked: $(printf '%s' "$_r" | head -c 60)"

# 3. The workstation has no direct network path to the internal segment.
_r="$(ws_curl "http://172.30.77.10:9200/")"
[ -z "$_r" ] && pass "workstation has no direct path to the internal network" \
    || fail "workstation has no direct path to the internal network" "leaked: $(printf '%s' "$_r" | head -c 60)"

say "== checks: secure DNS on the bastion"
# CoreDNS resolves the internal target name. Queried from the broker, which
# shares the bastion node's netns (on the internal segment, with DoT upstream).
_ip="$($RUNTIME exec acc-broker sh -c 'command -v dig >/dev/null 2>&1 || apk add -q bind-tools >/dev/null 2>&1; dig +short +time=3 @172.30.77.5 boundary.hashi.internal A' 2>/dev/null | grep -E '^[0-9]' | sed -n 1p)"
[ "$_ip" = "172.30.77.10" ] \
    && pass "bastion CoreDNS resolves internal target names" "$_ip" \
    || fail "bastion CoreDNS resolves internal target names" "got '$_ip'"

if net_report; then
    say ""
    say "Workstation reaches Boundary only:  http://$_bip:9200  (via SOCKS5 :1055)"
    say "Tear down: ./run-uat.sh --down"
fi
net_report
