#!/bin/sh
# UAT / smoke test for the HAProxy reverse-proxy stack. Proves the proxy
# terminates TLS with the local CA and forwards a real request to the demo
# backend, that proxy/security headers are applied, HTTP redirects to HTTPS,
# and an unknown Host gets no route (404).
#
#   ./run-uat.sh           # bring up, assert, leave running
#   ./run-uat.sh --down    # tear down and drop generated state
set -u

cd "$(dirname "$0")"
. ../../ci/net-uat-lib.sh

STACK=haproxy
COMPOSE_FILE=../docker-compose.yml
TLS_PORT=8443
HTTP_PORT=8080
APP_HOST=app.localhost
CERT_CN=$APP_HOST
CERT_SANS="whoami.localhost"

if [ "${1:-}" = "--down" ]; then
    net_down
    exit 0
fi

say "== HAProxy reverse-proxy UAT (TLS termination + backend routing)"

cat > .env <<EOF
# Generated by run-uat.sh — not for production use.
PROXY_IMAGE=docker.io/library/haproxy:3.2
BIND_ADDR=127.0.0.1
TLS_PORT=$TLS_PORT
HTTP_PORT=$HTTP_PORT
TLS_DIR=$(pwd)/tls
COMPOSE_NET_NAME=${STACK}-net-uat
EOF

net_init

# HAProxy wants cert+key in one PEM.
cat tls/tls.crt tls/tls.key > tls/haproxy.pem
chmod 644 tls/haproxy.pem

APP="https://$APP_HOST:$TLS_PORT"
RESOLVE="--resolve $APP_HOST:$TLS_PORT:127.0.0.1"

say "-- bringing up proxy + demo backend"
up whoami haproxy || { net_down; exit 1; }
ensure_running whoami-demo
ensure_running haproxy-proxy
wait_healthy haproxy-proxy 60 || { dumplog haproxy-proxy; net_report; exit 1; }
wait_http "$APP/" 60 '^(200)$' --cacert "$CA" $RESOLVE || {
    dumplog haproxy-proxy; net_report; exit 1; }

say "== checks"
check 200 "request reaches backend through TLS" --cacert "$CA" $RESOLVE "$APP/"
check_body "whoami-demo" "response body comes from the demo backend" \
    --cacert "$CA" $RESOLVE "$APP/"
check_body "X-Forwarded-Proto: https" "proxy sets X-Forwarded-Proto" \
    --cacert "$CA" $RESOLVE "$APP/"

_hdrs="$(curl -s -D - -o /dev/null -A "$UA" --cacert "$CA" $RESOLVE "$APP/")"
printf '%s' "$_hdrs" | grep -qi '^x-frame-options:' \
    && pass "security headers applied" \
    || fail "security headers applied" "no X-Frame-Options"

say "-- negative checks"
check 301 "plain HTTP is redirected to HTTPS" \
    --resolve "$APP_HOST:$HTTP_PORT:127.0.0.1" "http://$APP_HOST:$HTTP_PORT/"
check 404 "unknown Host gets no route" \
    -k --resolve "nope.localhost:$TLS_PORT:127.0.0.1" \
    "https://nope.localhost:$TLS_PORT/"
check 200 "certificate verifies against the UAT CA" --cacert "$CA" $RESOLVE "$APP/"

if net_report; then
    say ""
    say "Proxy:     $APP   (curl --cacert $(pwd)/tls/ca.crt --resolve $APP_HOST:$TLS_PORT:127.0.0.1 ...)"
    say "Tear down: ./run-uat.sh --down"
fi
net_report
